### ISSUE TITLE
Receiving this error- osrmTable function returns an error: Error: The URL sent to the OSRM public API is too long. Enter less sources or destinations

### ISSUE THREAD

**Issue by layzre** [rCarto/osrm#12]
Hi, first off, thanks for the awesome package!

I'm new to this package and have been experimenting with osrm . I tried the example code for  osrmTable(). Namely:

data("com")
distCom2 <- osrmTable(src = com[1:10,c("comm_id","lon","lat")],
                      dst = com[11:20,c("comm_id","lon","lat")])

This exact code worked just fine yesterday, however, when I try now, it is giving me this error:

osrmTable function returns an error: 
Error: The URL sent to the OSRM public API is too long. Enter less 
         sources or destinations.

I tried reducing the number of sources & destinations to one:

home = data.frame(001, -118.454642, 34.069432)
work = data.frame(002, -118.260938, 34.049268)
test = osrmTable(src=home, dst=work)

however, I am still receiving the same error. Trying all the other example codes within osrmTable() such as:
distCom <- osrmTable(loc = com[1:50, c("comm_id","lon","lat")])

also gives me the same error. I was hoping you could help me figure out a solution to this error and hopefully explain why this error did not appear before. Thanks in advance!

**Comment by rCarto** [comment]
The error seems to come from the OSRM public API, as my own OSRM server is still giving results without errors. 
The "Error: The URL sent to the OSRM public API is too long. Enter less sources or destinations." message is misleading as it appears every time the server gives no answer... I will correct that. 
I'll investigate the OSRM public API problem.

**Comment by layzre** [comment]
Ok great, thanks! Please keep me posted. Let me know if there's anything I can do on my end.

**Comment by rCarto** [comment]
I confirm that the problem comes from the OSRM public API . 
Trying one of their example won't work (http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=full&steps=true).

As they state: 
> Please note the API Usage Policy. Especially note that there are no guarantees regarding availability, stability or correctness of results. It's server to demonstrate OSRM, not a production-ready API.
(https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server)

The best way to avoid these kind of disturbance would be to install your own OSRM instance...

**Comment by layzre** [comment]
Ah I see. I figured the way around this would have to be downloading my own OSRM map. Would you by any chance know the best way to go about this? I'm fairly new to R and API.

**Comment by layzre** [comment]
Downloading the map and then integrating that map into the osrm functions in particular

**Comment by layzre** [comment]
specifically, installing the osrm map and integrating it into the osrm functions

**Comment by rCarto** [comment]
see https://github.com/Project-OSRM/osrm-backend/issues/2703

**Comment by rCarto** [comment]
To install an OSRM instance you would have to follow the steps describe in the wiki pages of the project : https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM

**Comment by layzre** [comment]
Thanks!

**Comment by daniel-j-h** [comment]
The OSRM demo server currently runs both a v4 endpoint as well as a v5 endpoint (different APIs, with v5 scheduled for shut down). During the last days the demo server has some hiccups mostly from us introducing lane handling and testing a new release.

Disclaimer: the demo server always runs from the latest master commit and uses a fresh planet every day. That is, we want the demo server to break on the planet instead of us not noticing problems.

We're happy to help with any problems, just ping us.
https://github.com/Project-OSRM/osrm-backend#contact
