### ISSUE TITLE
Replicating osrmIsochrone vignette script

### ISSUE THREAD

**Issue by mansonp** [rCarto/osrm#21]
I am assuming some other package change has caused the problem I am running into. The vignette for osrmIsochrone was working for me previously. But running the script now throws up an error on the line executing:

`  osm <- getTiles(spdf = iso, crop = TRUE, type = "osmtransport")` 

The function results in:
`Error in { : 
  task 2 failed - "arg 'X2' has dims=256, 256, 4; but need dims=X, 256, 3"`

I can step through the code and create the isochrones, but the underlying tiles are the issue. I can create other maps with the cartography package. So I suspect there is something with the spdf created with:

`iso <- osrmIsochrone(loc = src[6,], breaks = seq(from = 0,to = 30, by = 5))` 

Thanks

**Comment by rCarto** [comment]
Hello, 
The isohrone spdf you are creating should be fine. 
The problem comes from `cartography` and its use of `rosm` (the package used to download osm tiles). Both have been recently updated  to take into account modifications of osm servers APIs. Your problem should be fixed by updating `cartography` and `rosm`. Tell me if it still don't work after the update.

**Comment by mansonp** [comment]
I figured there was a dependency I was missing an update on - had gotten `cartography` but missed `rosm`. Thank you!
